language: go

services:
  - redis
  - memcached

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

env:
  global:
    - GO111MODULE=on
    - REDIS_ADDR=localhost:6379
    - MEMCACHE_SERVER=127.0.0.1:11211

install:
  - go get
